-- Inserir os planos de assinatura criados no Stripe
INSERT INTO "supplier_subscription_plans" (
  "id", 
  "planType", 
  "name", 
  "description", 
  "monthlyPrice", 
  "stripeProductId", 
  "stripePriceId", 
  "maxProducts", 
  "maxPartnerships", 
  "commissionRate", 
  "prioritySupport", 
  "advancedAnalytics", 
  "apiAccess", 
  "whiteLabel", 
  "dedicatedManager", 
  "customReports", 
  "slaGuarantee"
) VALUES
-- Plano Starter
(
  'starter-plan-001',
  'STARTER',
  'Plano Starter - Fornecedor',
  'Plano de entrada para fornecedores pequenos. Inclui até 50 produtos, até 20 parcerias ativas, comissão de 5%, suporte por email e dashboard básico.',
  4900,
  'prod_T7AOhCBDHoJItV',
  'price_1SAw52EQcZJjqJoqxNnYY1uH',
  50,
  20,
  0.05,
  false,
  false,
  false,
  false,
  false,
  false,
  false
),
-- Plano Growth  
(
  'growth-plan-001',
  'GROWTH',
  'Plano Growth - Fornecedor',
  'Plano para fornecedores em expansão. Inclui até 200 produtos, até 100 parcerias ativas, comissão de 3%, suporte prioritário, analytics avançado e integração com sistemas externos.',
  14900,
  'prod_T7AOrC7viRtUXk',
  'price_1SAw5REQcZJjqJoqb9K15ZHV',
  200,
  100,
  0.03,
  true,
  true,
  true,
  false,
  false,
  false,
  false
),
-- Plano Professional
(
  'professional-plan-001',
  'PROFESSIONAL',
  'Plano Professional - Fornecedor',
  'Plano para fornecedores estabelecidos. Produtos ilimitados, parcerias ilimitadas, comissão de 2%, suporte dedicado, white-label, relatórios customizados e gerente de conta.',
  29900,
  'prod_T7APElelSfW3Gg',
  'price_1SAw5aEQcZJjqJoqnQuC4EGO',
  null,
  null,
  0.02,
  true,
  true,
  true,
  true,
  true,
  true,
  false
),
-- Plano Enterprise
(
  'enterprise-plan-001',
  'ENTERPRISE',
  'Plano Enterprise - Fornecedor',
  'Plano corporativo para grandes fornecedores e distribuidores. Tudo do Professional + comissão negociável, SLA garantido, integração customizada, onboarding dedicado e suporte 24/7.',
  99900,
  'prod_T7AP7lmF2DegIa',
  'price_1SAw5hEQcZJjqJoqsukcAjbV',
  null,
  null,
  0.015,
  true,
  true,
  true,
  true,
  true,
  true,
  true
);